development:
  base_url: http://lvh.me:3000
  stripe_publishable_key: pk_test_xsPeLTHhU6DxQ1s6xW2D8e3A
  stripe_secret_key: sk_test_CQhga2YXSoTD6Miw3jMXKRjP
staging:
  base_url: http://thinkablelms.com
  stripe_publishable_key: pk_test_xsPeLTHhU6DxQ1s6xW2D8e3A
  stripe_secret_key: sk_test_CQhga2YXSoTD6Miw3jMXKRjP
production:
  base_url: http://thinkablelms.com
